import { useEffect, useState } from 'react'
import { money } from '../lib/format'
import { useRun } from '../state/RunContext'
import { api } from '../api'

export default function JournalsPage() {
  const { runId } = useRun()
  const [journals, setJournals] = useState<Array<Record<string, unknown>>>([])
  const [writebacks, setWritebacks] = useState<Array<Record<string, unknown>>>([])

  useEffect(() => {
    if (!runId) {
      setJournals([])
      setWritebacks([])
      return
    }
    api.journals(runId).then((r) => {
      setJournals(r.journals || [])
      setWritebacks(r.writebacks || [])
    }).catch(() => {
      setJournals([])
      setWritebacks([])
    })
  }, [runId])

  const posted = journals.filter((j) => j.status === 'POSTED').length

  return (
    <div className="stack">
      <div className="page-header">
        <div>
          <h1>Journal entries</h1>
          <p>Double-entry postings generated by the CrewAI flow (AR/AP/ADJ) with simulated ERP write-back.</p>
        </div>
      </div>

      <div className="grid-3">
        <div className="stat">
          <div className="label">Entries</div>
          <div className="value">{journals.length}</div>
        </div>
        <div className="stat">
          <div className="label">Posted</div>
          <div className="value">{posted}</div>
        </div>
        <div className="stat">
          <div className="label">Write-backs</div>
          <div className="value">{writebacks.length}</div>
        </div>
      </div>

      <div className="card">
        <div className="card-pad" style={{ borderBottom: '1px solid var(--line)' }}>
          <h2 className="card-title">Ledger</h2>
          <p className="card-sub" style={{ marginBottom: 0 }}>Dr / Cr pairs from create_journal_entries</p>
        </div>
        {!runId || journals.length === 0 ? (
          <div className="empty">
            <strong>No journals yet</strong>
            Run the CrewAI reconciliation flow first.
          </div>
        ) : (
          <div className="table-wrap">
            <table className="data">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Debit</th>
                  <th>Credit</th>
                  <th>Amount</th>
                  <th>Txn</th>
                  <th>Memo</th>
                </tr>
              </thead>
              <tbody>
                {journals.map((j) => (
                  <tr key={String(j.id)}>
                    <td className="mono">{String(j.id)}</td>
                    <td><span className="badge badge-brand">{String(j.entry_type)}</span></td>
                    <td>
                      <span className={`badge ${j.status === 'POSTED' ? 'badge-ok' : 'badge-warn'}`}>
                        {String(j.status)}
                      </span>
                    </td>
                    <td className="mono">{String(j.debit_account)}</td>
                    <td className="mono">{String(j.credit_account)}</td>
                    <td>{money(Number(j.amount))}</td>
                    <td className="mono">{String(j.transaction_id || '—')}</td>
                    <td>{String(j.memo || '')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  )
}
